- [aluminium, aluminum]
- [hob, cooktop]
- [gasoline, petrol]
- [embedded, embodied]
- [plane, air, aviation, aircraft, flight, airline, airplane, aeroplane, fly]
- [van, truck, lorry]
- [us, usa, america, american]
- [uk, britain, england, scotland, wales]
- [electric, electricity, grid, power]
- [combustion, burn, burning]
- [stack, flue, chimney]
- [motorbike, motorcycle]
- [train, rail, railway]
- [ship, ferry, boat]
- [taxi, cab]
- [country, nation, nationality]
- [ch4, methane]
- [n2o, nitrous]
- [co2, carbon]
- [ghg, greenhouse]
- [methodology, model]
- [data, dataset]
- [mass, weight]
- [residential, domestic]
- [cattle, cow]
